version: '3'

services:

    app:
        build: .
        restart: always
        container_name: app
        ports:
            - 8080:8080
        links:
            - mongodb
        depends_on:
            - mongodb
        networks: 
            - starwars-network

    mongodb:
        image: mongo:4.4.4
        restart: always
        container_name: mongodb
        networks: 
            - starwars-network
        ports:
            - 27017:27017
        volumes:
            - ./dbdata:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB_DATABASE=starwars
            - MONGO_INITDB_USERNAME=root
            - MONGO_INITDB_PASSWORD=root

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8085:8081
        networks: 
            - starwars-network
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_AUTH_USERNAME=root
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=root
        depends_on:
            - mongodb

networks: 
    starwars-network:
        driver: bridge